stages:
  - build
  - test
  - release
  - deploy
build-job:
 tags:
  - vm-shell
 stage: build
 script: 
  - echo "creating virtual environment for the project...."
  - virtualenv $[pwd]/venv
  - source $[pwd]/venv/bin/active
  - echo "Installing requirement file"
  - pip install -r requirements.txt
  - deactivate
 artifacts:
  paths:
    - $[pwd]/venv

test-job:
 tags:
   - vm-shell
 stage: test
 script:
  - echo "activating virtual environment"
  - source $[pwd]/venv/bin/activate
  - echo "running unit test"
  - python manage.py test djnagoapp
  - echo "cheking the server...."
  - python manage.py runserver &
  - sleep 10
  - curl -sSf http://localhost:8080 > /dev/null && echo "server is up"
  - sudo pkill python
  - deactivate
  - echo "successfully run pipeline"